#!/usr/bin/env python3
"""pack_res.py — convert res/*.png to RGB565 + A8, generate C arrays."""

import os, struct, sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

SCRIPT_DIR  = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
RES_DIR     = PROJECT_DIR / "res"
GEN_DIR     = PROJECT_DIR / "generated"

HEADER_MAGIC = b"LIMG"
PACK_MAGIC   = b"LRES"


def rgba_to_rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def convert_png(path):
    """Convert a PNG file to RGB565 pixels + A8 mask. Returns (name, w, h, pixels, alpha)."""
    img = Image.open(path).convert("RGBA")
    w, h = img.size
    data = img.getdata()

    pixels = []
    alpha  = []
    has_alpha = False

    for r, g, b, a in data:
        pixels.append(rgba_to_rgb565(r, g, b))
        alpha.append(a)
        if a != 255:
            has_alpha = True

    name = path.stem.upper()
    return name, w, h, pixels, alpha, has_alpha


def write_limg(path, w, h, pixels, alpha, has_alpha):
    """Write a single .limg binary file."""
    flags = 1 if has_alpha else 0
    fmt   = 0  # raw

    with open(path, "wb") as f:
        f.write(HEADER_MAGIC)                         # magic
        f.write(struct.pack("<H", w))                  # width
        f.write(struct.pack("<H", h))                  # height
        f.write(struct.pack("<B", flags))              # flags
        f.write(struct.pack("<B", fmt))                # format
        f.write(struct.pack("<H", 0))                  # reserved
        f.write(struct.pack(f"<{w*h}H", *pixels))      # RGB565
        if has_alpha:
            f.write(struct.pack(f"<{w*h}B", *alpha))   # A8


def write_lres(path, images):
    """Write the .lres resource pack."""
    count = len(images)
    idx_size = count * 32  # each entry: 20B name + 4B offset + 4B size + 2B w + 2B h
    data_offset = 16 + idx_size  # header(16) + index

    # Compute offsets
    entries = []
    off = data_offset
    for name, w, h, pixels, alpha, has_alpha in images:
        size = 12 + w * h * 2  # header + pixels
        if has_alpha:
            size += w * h      # alpha
        entries.append((name, w, h, off, size, has_alpha, pixels, alpha))
        off += size

    with open(path, "wb") as f:
        # Header
        f.write(PACK_MAGIC)
        f.write(struct.pack("<H", 1))       # version
        f.write(struct.pack("<H", count))
        f.write(struct.pack("<Q", 0))       # reserved

        # Index
        for name, w, h, off, size, has_alpha, _, _ in entries:
            name_bytes = name[:19].ljust(20, "\0").encode("ascii")
            f.write(name_bytes)                    # name[20]
            f.write(struct.pack("<I", off))        # offset
            f.write(struct.pack("<I", size))       # size
            f.write(struct.pack("<H", w))          # width
            f.write(struct.pack("<H", h))          # height

        # Data
        for _, w, h, _, _, has_alpha, pixels, alpha in entries:
            flags = 1 if has_alpha else 0
            f.write(HEADER_MAGIC)
            f.write(struct.pack("<H", w))
            f.write(struct.pack("<H", h))
            f.write(struct.pack("<B", flags))
            f.write(struct.pack("<B", 0))   # format
            f.write(struct.pack("<H", 0))   # reserved
            f.write(struct.pack(f"<{w*h}H", *pixels))
            if has_alpha:
                f.write(struct.pack(f"<{w*h}B", *alpha))


def write_c_array(f, name, values, elem_size):
    """Write a C array: const TYPE name[N] = { ... };"""
    etype = f"uint{elem_size*8}_t"
    n     = len(values)
    per_line = 16

    f.write(f"const {etype} {name}[{n}] = {{\n")
    for i in range(0, n, per_line):
        chunk = values[i:i+per_line]
        hex_vals = ", ".join(f"0x{v:0{elem_size*2}x}" for v in chunk)
        f.write(f"    {hex_vals},\n")
    f.write("};\n\n")


def generate_c(images, gen_dir):
    """Generate res_bundle.c and res_bundle.h."""
    c_path = gen_dir / "res_bundle.c"
    h_path = gen_dir / "res_bundle.h"

    # Sanitize names for C identifiers
    safe_names = []
    for name, _, _, _, _, _ in images:
        safe = name.replace("-", "_").replace(" ", "_")
        safe_names.append(safe)

    with open(c_path, "w") as f:
        f.write('// Auto-generated by pack_res.py — DO NOT EDIT\n')
        f.write('#include "res_bundle.h"\n\n')

        for (name, _, _, pixels, alpha, has_alpha), safe in zip(images, safe_names):
            write_c_array(f, f"res_pixels_{safe}", pixels, 2)
            if has_alpha:
                write_c_array(f, f"res_alpha_{safe}", alpha, 1)

        # ImageAsset table
        f.write(f"const ImageAsset kImageAssets[{len(images)}] = {{\n")
        for (name, w, h, _, alpha, has_alpha), safe in zip(images, safe_names):
            alpha_ptr = f"res_alpha_{safe}" if has_alpha else "0"
            f.write(f'    {{"{name}", {w}, {h}, res_pixels_{safe}, {alpha_ptr}}},\n')
        f.write("};\n\n")
        f.write(f"const int kImageAssetCount = {len(images)};\n")

    with open(h_path, "w") as f:
        f.write('// Auto-generated by pack_res.py — DO NOT EDIT\n')
        f.write('#pragma once\n')
        f.write('#include <stdint.h>\n\n')
        f.write('typedef struct ImageAsset {\n')
        f.write('    const char*     name;\n')
        f.write('    uint16_t        width;\n')
        f.write('    uint16_t        height;\n')
        f.write('    const uint16_t* pixels;\n')
        f.write('    const uint8_t*  alpha;\n')
        f.write('} ImageAsset;\n\n')
        f.write('#ifdef __cplusplus\n')
        f.write('extern "C" {\n')
        f.write('#endif\n')
        f.write(f'extern const ImageAsset kImageAssets[{len(images)}];\n')
        f.write(f'extern const int kImageAssetCount;\n')
        f.write('#ifdef __cplusplus\n')
        f.write('}\n')
        f.write('#endif\n')

        for (name, _, _, _, _, _), safe in zip(images, safe_names):
            f.write(f'extern const uint16_t res_pixels_{safe}[];\n')
            alpha_ptr = f"res_alpha_{safe}"
            f.write(f'extern const uint8_t  {alpha_ptr}[];\n')


def main():
    gen_dir = GEN_DIR
    gen_dir.mkdir(exist_ok=True)

    png_files = sorted(RES_DIR.glob("*.png"))
    if not png_files:
        print("ERROR: no PNG files found in res/")
        sys.exit(1)

    print(f"Found {len(png_files)} PNG files")

    images = []
    for path in png_files:
        name, w, h, pixels, alpha, has_alpha = convert_png(path)
        images.append((name, w, h, pixels, alpha, has_alpha))

        # Write .limg
        limg_path = gen_dir / f"{name}.limg"
        write_limg(limg_path, w, h, pixels, alpha, has_alpha)
        alpha_str = "A8" if has_alpha else "opaque"
        print(f"  {name:20s} {w}x{h}  {len(pixels)}px  alpha={alpha_str}  → {limg_path.name}")

    # Write .lres pack
    lres_path = gen_dir / "res_bundle.lres"
    write_lres(lres_path, images)
    lres_size = os.path.getsize(lres_path)
    print(f"\n  Pack: {lres_path.name} ({lres_size} bytes, {len(images)} images)")

    # Generate C source
    generate_c(images, gen_dir)
    c_size = os.path.getsize(gen_dir / "res_bundle.c")
    print(f"  Generated: res_bundle.c ({c_size} bytes)")
    print(f"  Generated: res_bundle.h")
    print("Done.")


if __name__ == "__main__":
    main()
